### ISSUE TITLE
calHook in HookExecutor needs refinement

### ISSUE THREAD

**Issue by damagefilter** [FallenMoonNetwork/CanaryLib#1]
callHook does not consider Plugin priorities yet, however it should. Changes must include:
- High and Critical priority Plugins must get hooks regardless of their cancel-state
- (Suggestion) Low priority Plugins could receive cancelled hooks for monitoring stuff.

**Comment by BluXDragon** [comment]
There's already passive for monitoring. Perhaps that should receive cancelled. I disagree with LOW.
You know, I'm thinking, you could always add another argument on RegisterListener "RecieveCancelled" true/false ._.

**Comment by damagefilter** [comment]
That'S what I meant. So that monitoring plugins would receive cancelled hooks still to monitor what happened to the hook.
