### ISSUE TITLE
Item.getMetaData kind of "corrupts" items, causing them to not stack properly

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#101]
The code provided below causes items to become what I call "dirty". Dirty items will not stack with clean items, only other dirty items.

```
    @Command(aliases = { "breakitem" },
            description = "Try to break an item",
            permissions = { "testingplugin.command.breakitem" },
            toolTip = "/breakitem",
            min = 1)
    public void breakItemCommand(MessageReceiver caller, String[] split){
        if (caller instanceof Player){
            Player p = ((Player) caller).getPlayer();
            Item item = p.getItemHeld();
            if (item == null)return;
            CompoundTag nbt = item.getMetaTag();
        }
    }
```

Unnecessary lines have been trimmed. If you feel the need to see them;
http://pastebin.com/Au14xaF4

Evidently the issue lies in item.getMetaTag(); - once this code is performed, the item will no longer stack with new "clean" items.

**Comment by darkdiplomat** [comment]
https://github.com/FallenMoonNetwork/CanaryLib/commit/bb22f2a0b5e866d141ce803d13d5ab022d179a4a addresses this
