### ISSUE TITLE
Logman.logStacktrace() (or Canary.logStackTrace()?) is not capitalized correctly

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#104]
The T, specifically.

I noticed it because the capitalization is not the same as "Canary.logStackTrace()", which annoyed me >.>

Not sure if you'd even want to change this but yeah. Here's another tasty issue report about something so minor :D

**Comment by darkdiplomat** [comment]
as a plugin dev  you should be using Logman retrieved from the Plugin class. Canary.log\*  is meant for internal use.

**Comment by damagefilter** [comment]
Apart from that, although grammatically not quite correct, "Stacktrace" is meant to be a single word.
(Because it looks better :P)

**Comment by ayyron-dev** [comment]
What is the verdict here? closed?

**Comment by damagefilter** [comment]
The verdict is that we should refactor Canary.logStackTrace to Canary.logStacktrace
