### ISSUE TITLE
AnvilUseHook.getAnvil() breaks renaming items

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#106]
```
    @HookHandler
    public void onAnvilUse(AnvilUseHook hook){
        Anvil anvil = hook.getAnvil();
    }
```

The above code (alone) causes renaming items to break. When sticking an item in purely to rename it, after taking out the new item, there is no anvil use noise. When you close the inventory screen, you drop the item. The item dropped has the old name.
So essentially, the server thinks it never happened.

**Comment by darkdiplomat** [comment]
Im not sure what you are trying to say, but I am unable reproduce any issues with the AnvilUseHook.

**Comment by BluXDragon** [comment]
I can't actually reproduce the issue anymore either. I hate when this happens ._.

**Comment by damagefilter** [comment]
Reopen when it happens again.
