### ISSUE TITLE
Open GUI Interface

### ISSUE THREAD

**Issue by Larry1123** [FallenMoonNetwork/CanaryLib#111]
Just putting this up as a reminder.
Make interface to open GUIs (Chest, Workbenches, ect.)

**Comment by WWOL** [comment]
Opening a simple inventory is extremely easy, not sure about the others but it shouldn't be too hard.
Is someone already looking into this?

WWOL

**Comment by damagefilter** [comment]
no, please go ahead if you want to, just assign this thing to you so the others know.

**Comment by darkdiplomat** [comment]
Just a note to add to this, it should also allow for custom (sized) inventories to be opened as that is possible with the native code for Inventory GUI's

**Comment by WWOL** [comment]
I have a little bit done on this but run out of time. I could just pastebin the code and let someone else do it if you guys want it done.

WWOL

**Comment by darkdiplomat** [comment]
Forgot to close this with https://github.com/FallenMoonNetwork/CanaryLib/commit/246d5980c46073a8ca88251dd5ad60e846b3fc4a

For the most part this is good enough, some inventories may require more special attention
