### ISSUE TITLE
TeleportHook reason

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#112]
If at all possible, I'd like TeleportHook to have a getReason() method.
This should be simple enough, I imagine you'd use a TeleportReason enum or something.

But the method Entity.teleportTo(Location) should also come with a parameter to set the reason (by default it would just be "PLUGIN_DEFAULT" or something), eg Entity.teleportTo(loc, TeleportReason.PLUGIN). This would be useful for plugins that change the mechanic of existing teleport reasons, plugins that want to interfere with things like teleportation commands but not things such as ENDERPEARL, and such.

Two different PLUGIN teleport types should exist so that we know which teleports have been explicitly handled by a plugin already.

Or, if you see why this would be useful and can think of a better way, do that. I don't know, this was just my first idea on the matter.

**Comment by WWOL** [comment]
A TeleportReason interface. Canary could provide the simple defaults, such as GENERIC_PLUGIN and CANARY_COMMAND or something similar. Then a plugin can make its own reason. It could even extend GENERIC_PLUGIN reason.

WWOL

**Comment by darkdiplomat** [comment]
https://github.com/FallenMoonNetwork/CanaryLib/commit/ecbfb56ae50b4e4d6b80330e71b8cd9032dc2cf3
