### ISSUE TITLE
EntityDeathHook not being called when a Player dies

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#115]
With the below code, on killing entities (such as spiders, which was my test), the "something died." message will appear.

However, when a player dies (via falling, fire, or being killed by zombies - those were my tests), not even the "something died." message appears, let alone the "a player died!".

```
    @HookHandler
    public void onEntityDeath(EntityDeathHook hook){
        System.out.println("something died.");
        if (hook.getEntity() instanceof Player){
            System.out.println("A player died!");
        }
    }
```

**Comment by darkdiplomat** [comment]
https://github.com/FallenMoonNetwork/CanaryLib/blob/master/src/main/java/net/canarymod/hook/entity/EntityDeathHook.java#L13

**Comment by BluXDragon** [comment]
What is the reasoning behind this, exactly?

**Comment by darkdiplomat** [comment]
Player death is called in a different location and they don't sync up. Plus PlayerDeathHook has been there for a while and has stuff to change/disable the death message

**Comment by BluXDragon** [comment]
I was under the impression changing the message in EntityDeathHook.getDamageSource() was the way to do that.
Oh well, as long as it all works I guess. I still think it's strange.

Edit: can't actually get DamageSource from PlayerDeathHook D:

**Comment by darkdiplomat** [comment]
I know, I haven't gotten to adding it yet.

**Comment by BluXDragon** [comment]
Gah I can't get the NBT data of the player's entity using PlayerDeathHook either! It gets cleared before the hook is called!
I don't like it D:

**Comment by darkdiplomat** [comment]
NBT data isn't really "cleared"  it always dynamically generated

**Comment by BluXDragon** [comment]
Well you know what I meant. What my problem is ._.
