### ISSUE TITLE
TeleportHook.getDestination() location's rot/pitch are swapped

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#116]
Code and a picture woo!

```
    @HookHandler
    public void onTeleport(TeleportHook hook){
        final Player player = hook.getPlayer();
        player.sendMessage("PROT: "+player.getRotation());
        player.sendMessage("PPIT: "+player.getPitch());
        player.sendMessage("LROT: "+hook.getDestination().getRotation());
        player.sendMessage("LPIT: "+hook.getDestination().getPitch());
    }
```

![GitHub Logo](https://dl.dropboxusercontent.com/u/62700505/Pictures/MC/javaw%202013-06-19%2021-11-06-83.png)

**Comment by darkdiplomat** [comment]
How do you know it's not just wrong in Player? :P

**Comment by BluXDragon** [comment]
I suppose my code example does leave that possibility, but the un-snipped version does include actually teleporting to that location and it does mess up the pitch/rot.

**Comment by darkdiplomat** [comment]
fix in recode: https://github.com/FallenMoonNetwork/CanaryRecode/commit/b0a2aac5c9fba85aea38a1b56eaa54b80f3e1556
