### ISSUE TITLE
Built in Multiworld compatible permissions.

### ISSUE THREAD

**Issue by ayyron-dev** [FallenMoonNetwork/CanaryLib#118]
The title says it all. This way we have better compatibility across Multiworld plugins, and cleaner data storage for them as well.

My idea, add a 'worlds' String variable List to PermissionsAccess,  Then add a method to User and Groups for hasPermission(String permission, World world),  we can leave in the hasPermission(String permission) for backwards compatibilty and for those plugins that just don't give a damn about multiworld.

EDIT:  I also realize people may want, per world Groups, I have no thoughts on that at the moment as I'm about to head out the door, but I'm sure its doable, also whomever wrote the permissions section ( @damagefilter I think?) might have some better Ideas anywho.

**Comment by BluXDragon** [comment]
I was going to say in IRC, per world groups might work better. But we might want people to have the same group across all... So yeah.

If it's implemented as somners says, I hope the list can remain empty for "all worlds", or maybe a wildcard?

**Comment by ayyron-dev** [comment]
I was thinking something like "*" for all worlds.

**Comment by damagefilter** [comment]
Regarding permissions, I have the idea of a multiworld-centric implementation of the PermissionProvider, which would indeed require another String in PermissionAccess. However, I think this should be an extra DbAccess object.
So we keep the two implementations separate.

About those per-world groups - this is gonna be a little bit trickier.
We would need to talk about this in more detail as to how it can work with another permissionprovider implementation aswell as if the groups as they are might even suffice. Also the possibility of leaving this (advanced) logic to a plugin.

**Comment by damagefilter** [comment]
Ah, yes. Done. It comes as API. The logic needs to be implemented by a plugin as there are MANY ways to do it.
Even I can think of at least 2 ^^
