### ISSUE TITLE
ServerTickHook is unused

### ISSUE THREAD

**Issue by nosefish** [FallenMoonNetwork/CanaryLib#119]
Tried to use it in a PluginListener - didn't work. Searched the source trees of CanaryLib and CanaryMod - the only result was the class definition in CanaryLib/src/main/java/net/canarymod/hook/system/ServerTickHook.java

**Comment by darkdiplomat** [comment]
it was put on hold. debating on whether to proceed with implementation and where the best place for it was.

**Comment by BluXDragon** [comment]
In theory, ServerTickHook wouldn't have as many CME's as TaskManager tasks, wouldn't it?
I was having issues accessing a database with TaskManager tasks (as you know), but in a hook it probably would have worked fine...

**Comment by darkdiplomat** [comment]
Thats because TaskManager is asynchronous to the Server and the Server doesn't do many things "thread safe"
ServerTask was made to help with being more synchronous

**Comment by nosefish** [comment]
It would be really neat to have this, especially if it were called at the end of a tick - would give plugins a chance to reliably poll changes that are not visible through hooks. Another thing that it would allow is for other threads to synchronize on ticks, or delay tasks for a certain number of ticks.

With the <code>ServerTaskManager</code> and the exisiting hooks, there is no way to reliably determine if a world tick has occurred. The <code>ServerTaskManager</code> executes up to 50 times more often than the world, but the worlds may also tick several times in a row without the <code>ServerTaskManager</code> running tasks in between.
It is possible to determine that the world must have been ticked at least once between two runs of a <code>ServerTask</code> by carefully watching the system time, but under load this has a good chance of missing updates, because the <code>ServerTaskManager</code> and the tick loops are asynchronous.
This makes it impossible for a plugin to do anything that requires tick-exact timing, For example I'd like to be able to collect updates from the <code>RedstoneChangeHook</code> and decide what to do after all updates for a tick have rolled in.

@BluXDragon I recommend to read the book "Java Concurrency in Practice" by Brian Goetz. In essence, do not access the world in any way from outside the server thread. Writes are a recipe for crashes and world corruption, and reads can give you (very) outdated or inconsistent results - it might seem to work fine on your machine, but when running on a different CPU it may fail spectacularly for no obvious reason.
You can make copies of resources you need to access in a <code>ServerTask</code> run through the <code>ServerTaskManager</code>, or in a method called by a hook, work on the copy in another thread, then submit a <code>ServerTask</code> to write the results to the world. Very often, this is slower than just running the code in the server thread (and you run into the timing issues I described above, unless we get this hook or something similar), so you'd have to test how both variants perform under load.

**Comment by darkdiplomat** [comment]
https://github.com/FallenMoonNetwork/CanaryRecode/commit/fb7c6e1d912ee2a3f08fa27004efba9d927a1529
