### ISSUE TITLE
new methods

### ISSUE THREAD

**Issue by spenk** [FallenMoonNetwork/CanaryLib#12]
couldnt find some methods

player.getInventory.getItemFromSlot();
and world.Explode(x,y,z,power);
player.isOp();
player.setOp(): ?

also
some replacement for 
oworld.a(new OEntityLightningBolt(oworld, player.getX(), player.getY(), player.getZ()));?

**Comment by Jarvix** [comment]
I will look into most methods. The isOp and setOp is done via the canary.vanilla.op permission . Use player.hasPermission().

**Comment by spenk** [comment]
thanks
