### ISSUE TITLE
Request: a way to get a list of all currently loaded chunks

### ISSUE THREAD

**Issue by nosefish** [FallenMoonNetwork/CanaryLib#131]
The old CanaryMod has the <code>World.getLoadedChunks</code> method to get all chunks of a world that are currently loaded, which is very useful when a plugin that scans chunks for certain Blocks/Entities/TileEntities has to be reloaded or is enabled after a world has been loaded. (e.g. CraftBook-Extra does this to find all loaded self-updating ICs)

I'd like to have a way to accomplish this in the recode, too, without having to resort to accessing Minecraft's <code>World.b.g</code> (in 1.6.2) directly.

**Comment by damagefilter** [comment]
We shall re-implement that feature!
