### ISSUE TITLE
Documentation mismatches in World

### ISSUE THREAD

**Issue by nosefish** [FallenMoonNetwork/CanaryLib#132]
For
<code>isChunkLoaded(int x , int z)</code>, 
<code>getChunk(int x , int z)</code>, and 
<code>loadChunk(int x, int z)</code>
the documentation states that they take chunk coordinates, when in fact world coordinates are expected by the implementation in CanaryRecode.

**Comment by 14mRh4X0r** [comment]
Shouldn't this be an issue on CanaryRecode, since CanaryLib defines the API?

**Comment by darkdiplomat** [comment]
Recode corrected to follow specifications laid out in CanaryLib https://github.com/FallenMoonNetwork/CanaryRecode/commit/4f3d117cc1f8655f6b867fadff87500615157db1
