### ISSUE TITLE
Request: a way to simulate a right-click on a block

### ISSUE THREAD

**Issue by nosefish** [FallenMoonNetwork/CanaryLib#133]
I'd like to switch a lever from a plugin. As explained in https://github.com/FallenMoonNetwork/CanaryRecode/issues/64, all my attempts to accomplish that have failed so far.

CanaryMod's <code>Block</code> has the method <code>boolean rightClick(Player clicker)</code>, which makes this very easy (<code>null</code> players work for many block types).

**Comment by nosefish** [comment]
Less than 15 minutes - must be a new record. You people are awesome, thanks!

**Comment by darkdiplomat** [comment]
I just happen to be working on various things at the time and figured i could get this knocked out quickly
