### ISSUE TITLE
CommandBlock not recognised by Commands

### ISSUE THREAD

**Issue by damagefilter** [FallenMoonNetwork/CanaryLib#135]
Most commands check if a MessageReceiver is Server or Player,
however they do not take into account the CommandBlock, which is also a
MessageReceiver. So in order to fix that, a different logic must be used.

**Comment by WWOL** [comment]
As a quick fix could we just call the server code for command blocks? Some messages would be wrong but at least most would work.
As for some other way of doing it I don't know. Maybe some sort of PlayerBackedMessageReciever or WorldMessageReciever for ones that exist in the world.

WWOL

**Comment by damagefilter** [comment]
The moment you're looking at all the commands you could just take the time and think if it needs any different logic.
Most of them would work the same as if the server was invoking it though, that's right.

Apart from the fact that they have restricted permissions, so one should definitely check if it does permission checks or not. If it doesn't that needs to be changed (not for server, only for CommandBlock)
