### ISSUE TITLE
player removePotionEffect methods

### ISSUE THREAD

**Issue by svdragster** [FallenMoonNetwork/CanaryLib#138]
removeAllPotionEffects();
removePotionEffect(PotionEffect);

Would be nice if those were added for LivingBase, I couldn't find a different way to remove them except a workaround with high amplifier.

**Comment by BluXDragon** [comment]
Just pointing out, LivingBase is what you want this on. This means it applies for EntityLiving as well as Player. These two things were separated at some point, apparently.

**Comment by 14mRh4X0r** [comment]
Yeah, in 1.6 IIRC

**Comment by darkdiplomat** [comment]
My Linux drive went down and i don't get my new one till next week, but I will remember to look into this and move the methods around.

**Comment by damagefilter** [comment]
Yeah, mister one man show :p
