### ISSUE TITLE
player.setLevel/removeLevel/addLevel

### ISSUE THREAD

**Issue by svdragster** [FallenMoonNetwork/CanaryLib#139]
Since there is already getLevel those other methods would be nice.

**Comment by darkdiplomat** [comment]
getLevel is more of an informative method as its not an independent field, total experience points causes the change in level so setting just a level would have little to no effect as is.

**Comment by darkdiplomat** [comment]
on a side note, I will look into adding convenience methods to get the level wanted

**Comment by damagefilter** [comment]
Stealin' yo work! :P
On a side note ... (pun intended) - a method to convert back experience points to levels would be funky.
But my brain doesn't want to reverse that formula properly atm.
