### ISSUE TITLE
player.setMotion only runs when player gets fall damage

### ISSUE THREAD

**Issue by svdragster** [FallenMoonNetwork/CanaryLib#141]
```
public void onBlockPlace(BlockPlaceHook hook) {
    if (hook.getBlockPlaced().getType() == BlockType.Dirt) {
        Canary.getServer().broadcastMessage("BraveJump");
        hook.getPlayer().setMotionY(100);
    }
}
```

If I place a DirtBlock, it writes BraveJump. But only gives me the motion if I get fall damage in survival or adventure mode.

**Comment by darkdiplomat** [comment]
That seems a bit extreme for a motion.

Either way I have noticed an issue with the methods and variables and am working to correct them.

**Comment by darkdiplomat** [comment]
https://github.com/FallenMoonNetwork/CanaryRecode/commit/ae64fc78ce9aed28ede478c29d61e8ee460ba0e0
