### ISSUE TITLE
newItem(ItemType)

### ISSUE THREAD

**Issue by spenk** [FallenMoonNetwork/CanaryLib#145]
Canary.factory().getItemFactory().newItem(ItemType.glass) creates an item with the amount of 0, it should be 1 as in the javadocs.

**Comment by darkdiplomat** [comment]
The javadocs show  Damage 0, stack size 0
http://docs.visualillusionsent.net/CanaryLib/1.0-RC-3/net/canarymod/api/factory/ItemFactory.html#newItem(net.canarymod.api.inventory.ItemType)
