### ISSUE TITLE
removeItem does not work as its supposted to do

### ISSUE THREAD

**Issue by spenk** [FallenMoonNetwork/CanaryLib#146]
Item item = player.getInventory().getHelmetSlot();
player.getInventory().removeItem(item);

this should remove the item from the helmed slot but it removes the item that matches the itemType from the inventory.

**Comment by darkdiplomat** [comment]
NO

Remove Item has always been recursive to remove items that match a type.

setSlot(slotIndex, (Item)null)  should be used to clear slots specifically
