### ISSUE TITLE
im missing propertiesfile methods

### ISSUE THREAD

**Issue by spenk** [FallenMoonNetwork/CanaryLib#15]
couldnt find any propertiesfile methods are the method names changed or isnt it implemented yet

**Comment by Jarvix** [comment]
I don't exactly understand what you mean. Maybe you can join IRC and we can explain.

ConfigurationFile is used to work with property file-style configuration files.

**Comment by damagefilter** [comment]
I'm closing this as it's highly likely that he means ConfigurationFile which is the 1to1 replacement for PropertiesFile.
