### ISSUE TITLE
ConfigurationFile paths

### ISSUE THREAD

**Issue by WWOL** [FallenMoonNetwork/CanaryLib#17]
When creating a ConfigurationFile the path must be split by a / for the auto creation to work. This caused a bit of trouble when I was using File.seperator and wondering why it didn't work. I had to look at the source to figure it out. Perhaps it should use lastIndexOf(File.seperator) instead of lastIndexOf("/")? Or just replace all File.seperator with "/"?

Thoughts?

WWOL

**Comment by 14mRh4X0r** [comment]
It would indeed be better if we'd use File.separator instead of "/".
