### ISSUE TITLE
Register commands to Help system

### ISSUE THREAD

**Issue by damagefilter** [FallenMoonNetwork/CanaryLib#19]
That might be a tricky thing to do as the help system is probably not loaded when the commands enum is processed
and therefore there is no access to the Help system.

**Comment by 14mRh4X0r** [comment]
We should watch #24 on this.

**Comment by damagefilter** [comment]
CommandManager of #24 should auto-register a command to the help system in registerAll(...) / addCommand(...) after the command has been added to the list. So people wouldn't need to register the help extra.
