### ISSUE TITLE
Implement a modular command system?

### ISSUE THREAD

**Issue by 14mRh4X0r** [FallenMoonNetwork/CanaryLib#24]
It's possibly preferable to implement a modular command system for both native and plugin commands, where plugins can add commands using this.addCommand(CommandHandler, String command...), where CommandHandler takes a help description much like BaseCommand in CanaryMod.

**Comment by Jarvix** [comment]
What do you mean with modular?

**Comment by damagefilter** [comment]
That could mean the removal of the actual command hook and rather work with commands that are added to the system.
I kinda like that.

**Comment by 14mRh4X0r** [comment]
Yes, much like the current Canary does with PlayerCommands, but providing a piece of additional security by adding it as a final method to Plugin, so other plugins cannot remove your commands.
