### ISSUE TITLE
Allow plugins to implement custom databases.

### ISSUE THREAD

**Issue by Jarvix** [FallenMoonNetwork/CanaryLib#26]
There is a problem to be solved before this can be implemented: load order. Plugins are loaded after the database.

**Comment by damagefilter** [comment]
That means there needs to be a load point before database loads, so custom implementations can be made available.

**Comment by Jarvix** [comment]
I was thinking about a database mount-point, no dependency checking there. it will load it and call enable on it very early. in there only configuration can be accessed.

**Comment by damagefilter** [comment]
I'll implement this.

**Comment by damagefilter** [comment]
Done. Closing.
