### ISSUE TITLE
addition hook CommandCheck

### ISSUE THREAD

**Issue by spenk** [FallenMoonNetwork/CanaryLib#27]
i want to see a commandcheck hook where you can allow or deny the command skipping the permissions

**Comment by damagefilter** [comment]
We'll see how exactly that can be integrated with the new command system and where.

**Comment by damagefilter** [comment]
Deprecated. Will not be implemented.
Use onCommand hook in the future to cancel commands,
use the command system to register commands to the system.
Closed.
