### ISSUE TITLE
missing rot methods

### ISSUE THREAD

**Issue by spenk** [FallenMoonNetwork/CanaryLib#29]
im missing player.rotX y z etc can these be implemented
(also bump for fixing signchange :))

**Comment by Jarvix** [comment]
Did you see the setrotation gettotation and pitch methods in Entity?

**Comment by spenk** [comment]
no i didnt but can this also be for Player
if now how do i make a player an entity

**Comment by damagefilter** [comment]
Excuse me for a second: LOLOLOLOLOLTROLLOLOLOLOLRTROLLTROLLOLOLOL

Now.
Try player.\* again.

**Comment by Jarvix** [comment]
Spenk, read about SUBCLASSING. Player is a subclass of EntityLiving which is a subclass of Entity. SOO Player has ALL  methods that are in EntityLiving and in Entity.

**Comment by spenk** [comment]
ah yes i saw the getRotation methods already but not getRotationY(); x or z wich was earlier implemented in player.getLocation.rotY();

**Comment by spenk** [comment]
ItemEntity.destroy();
that one isnt added yet :) correct me is it is
i saw entity.destroy though

**Comment by 14mRh4X0r** [comment]
This issue CLOSED. Means you don't comment on it unless you have a reason to reopen it.
