### ISSUE TITLE
onBlockRightClicked issues

### ISSUE THREAD

**Issue by SirPsp** [FallenMoonNetwork/CanaryLib#30]
RightClickHook.getBlockPlaced() is actually the block you click, and getBlockClicked() is null if your hand is empty but the type is not what you hold, it's always from 1 to 5 depending on what direction you're facing.

Also, the item in your hand is null (or has id 0) the first time you right click, but after that it gets the correct id. Might be only for items you have when you log in.

I think it's only for onBlockRightClicked because onBlockPlace works fine.

**Comment by damagefilter** [comment]
Fixed in Recode :)
Closing.
