### ISSUE TITLE
Arrows don't shoot

### ISSUE THREAD

**Issue by gregcarlin** [FallenMoonNetwork/CanaryLib#32]
When I fire a bow, I can pull it back fine, but when I release it no arrow comes out. The arrow is removed from my inventory, but an inventory refresh returns the arrow and the restores the damage on the bow.

**Comment by damagefilter** [comment]
Actually I suppose that the source of this is the same as for the workbench issue. Not sure but I would say both use OSlot for some stuff or something along that line... Just saying.

**Comment by damagefilter** [comment]
Fixed this.
Next time, please commit bugs concerning vanilla behaviour (stuff that derivates from vanilla behaviour, unrelated to stuff that CanaryLib provides) to CanaryRecoed. Thanks :)
