### ISSUE TITLE
A couple requested methods

### ISSUE THREAD

**Issue by gregcarlin** [FallenMoonNetwork/CanaryLib#35]
I've been working a lot with the newest creeper (0.3), and I have found a need for a couple of methods:

playerInstance.isBlocking() - Returns whether or not the player is blocking with a sword
playerInstance.hasPotionEffect(PotionEffect e) - Check if player has a give potion effect. I am looking for this one in particular, but I presume that a whole potion effect API needs to be added because I don't seem to see anything like it in the docs.
vehicleInstance.setPassenger(Entity e) - I swear this existed before the update (not sure if it ever worked)

EDIT: Forgot to mention entityInstance.remove(), entityInstance.destroy() or something similar.
EDIT2: Just remembered playerInstance.isInVehicle() for determining whether or not a player is in a boat or minecart

**Comment by WWOL** [comment]
The first two both look easy. Adding a whole potion API would require a bit of thought though.

WWOL

**Comment by damagefilter** [comment]
There was indeed a vehicle.setPassenger() however, I didn't find a way to actually implement that and removed it.
We gonna take care of the potions API, it should be there some day anyway.
