### ISSUE TITLE
Factory

### ISSUE THREAD

**Issue by WWOL** [FallenMoonNetwork/CanaryLib#40]
Make factory classes to get around the fact the plugin devs can't go new Item() because it is an interface.
Without a factory devs have to add CanaryMod the the build path and use new CanaryBlock().

@damagefilter 
@Jarvix 
Thoughts?

The way I have it set out at the moment is everything is in the net.canarymod.api.factory package.
For a dev it is simple.
Canary.factory().itemFactory().newItem(int id);
There are lots of overloads for handling enchantments, damage etc.

WWOL

**Comment by damagefilter** [comment]
Sure thing man. Seems like the better idea to use a central factory than cluttering it all over the code.

**Comment by damagefilter** [comment]
Done. Closed.
