### ISSUE TITLE
Add Damage Values where necessary.

### ISSUE THREAD

**Issue by ayyron-dev** [FallenMoonNetwork/CanaryLib#42]

**Comment by damagefilter** [comment]
How#s that thing coming along? Can it be closed? ^^

**Comment by ayyron-dev** [comment]
Need to check that everywhere that uses an implementation of inventory and item use the proper methods. Been away, I'll be around tomorrow though.

**Comment by damagefilter** [comment]
Okay, cool! :)

**Comment by ayyron-dev** [comment]
I did some looking and cannot fine anywhere where we need to add damage values. Closing.
