### ISSUE TITLE
Command (Small) Refactor

### ISSUE THREAD

**Issue by WWOL** [FallenMoonNetwork/CanaryLib#50]
@damagefilter 
@darkdiplomat 

When adding commands the logic is split into console and player methods. Often for simple commands these are the same. The only thing different is permission checking.
Why can't these be merged into the one method. MessageReciever can check permissions and send messages to the command caller so I see no reason to split it.
That said for the more advanced commands (or where the console can't be used) could still split the logic.

Thanks,

WWOL

**Comment by damagefilter** [comment]
If you don't want or need to split the logic, there is no need to. You can do most of the things with the MessageReceiver already. That's no problem. I just used to split them up in some commands to give the console a different output.

Also thanks for making the command :D

**Comment by WWOL** [comment]
Thanks, I'll fix up the split ones that don't need to be split and add any new commands I think of over the weekend.

WWOL

**Comment by damagefilter** [comment]
The already existing commands are already split (or not split) up properly. You don't need to go through them ;)

But if you find a missing command, go ahead and add it.
