### ISSUE TITLE
CommandSystem checks for CommandBlock

### ISSUE THREAD

**Issue by darkdiplomat** [FallenMoonNetwork/CanaryLib#52]
so we don't get a CommandException when using a CommandBlock to execute commands

**Comment by damagefilter** [comment]
Looking into it now.

Edit: We need to discuss that in more detail I think.

**Comment by WWOL** [comment]
Could CommandBolock be a MessageReciever or am I thinking all wrong here?

WWOL

**Comment by damagefilter** [comment]
It already implements MessageReceiver.
It'd be treated as server (god permission) so the thing is how to effectively disable commands on it before permission checks.

**Comment by WWOL** [comment]
It's messy but have a special "ComandBlock" permission. However this would be for all command blocks not individual ones. I'm sure you'll find a better way.

WWOL

**Comment by damagefilter** [comment]
CommandBlock re-routes its commands to Server and acts according to a list of allowed commands.
This should fix this issue.
