### ISSUE TITLE
Player setDisplayName() sends the packet to the player you are changing

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#56]
As title as description. This is a problem as it causes the player in question to lose control over their own character (you will stand there unable to do anything until you relog).

On fixing this, I would also suggest you allow the player's display to be set to any form of EntityLiving. It does work, I have done it before, you simply send a packet spawning an Entity (such as a zombie) containing the player in question's entity ID. The only different is it's a different packet.

**Comment by damagefilter** [comment]
Fixed, closing :)
