### ISSUE TITLE
Request: EntityLiving.setCustomName()

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#58]
Methods to set the "CustomName" and "CustomNameVisible" tags on EntityLiving.

http://www.minecraftwiki.net/wiki/Chunk_format#Mobs

**Comment by darkdiplomat** [comment]
closed with https://github.com/FallenMoonNetwork/CanaryLib/commit/4f52a68da149a64e854d31440a950216bbcdf8b0
