### ISSUE TITLE
EntityRightClickHook not called when rightclicking NonPlayableCharacter and Villager

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#59]
As title as description.

Updated to include Villager

**Comment by ayyron-dev** [comment]
Look at the behavior class.

**Comment by BluXDragon** [comment]
I am aware of this now but what if we want to have an effect on all NPC's (such as, say, deleting an entity when rightclicking them with an item), including those that weren't created by the same plugin. Are we to iterate through entities and apply behaviors to NPC's as they need them? I just think having EntityRightClickHook called too would be useful for situations where it's not specific to an NPC (or any NPC, when it applies to all Entities).

**Comment by BluXDragon** [comment]
Updated to include Villager.

**Comment by ayyron-dev** [comment]
Tomorrow is a coding day for me since today wasn't. Any others you're aware of?

**Comment by ayyron-dev** [comment]
fixed this with https://github.com/FallenMoonNetwork/CanaryLib/commit/5f5c315268297f3180b26e5488ae097c3c76b2d6
