### ISSUE TITLE
Request: /sethome [playername] should be a thing

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#69]
Being able to set other players homes by default would be nice.

**Comment by darkdiplomat** [comment]
DarkDiplomat approves! @damagefilter get on it :3

**Comment by damagefilter** [comment]
You can do setwarp HOME_PLAYERNAME (all uppercase letters) ^^
I shall be adding it nevertheless

**Comment by damagefilter** [comment]
Ah, yes. I did that one.
