### ISSUE TITLE
World.getBlockAt(x, y, z)

### ISSUE THREAD

**Issue by gregcarlin** [FallenMoonNetwork/CanaryLib#7]
Maybe I'm just missing it, but I can't seem to find this method. I think it's pretty crucial though.

**Comment by Jarvix** [comment]
It is in Dimension. The different between Dimension and World has been much clearer and better in Creeper.
A world has 3 dimensions. A dimension is thus Nether, Normal and End.
Dimension.getBlockAt() is there.

You can get the dimension from a world with World.getEnd() .getNether() .getNormal() or with .getDimensions().

**Comment by gregcarlin** [comment]
Ahh sorry about that.
