### ISSUE TITLE
Spawning Particles has no visible effect

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#74]
As title as description. Spawning Particles has no visible effect.
No related errors.

**Comment by ayyron-dev** [comment]
Can you post your code Calls to these methods?

**Comment by BluXDragon** [comment]
Updated. Every Aux effect I've tried work except BONE_MEAL. No particles work.

```
AuxiliarySoundEffect p = new AuxiliarySoundEffect(AuxiliarySoundEffect.Type.POTION_BREAK, (int)targetPlayer.getX(), (int)targetPlayer.getY()+1, (int)targetPlayer.getZ());
targetPlayer.getWorld().playAUXEffectAt(targetPlayer, p);
if (BxCommons.debug)System.out.println(caller.getName()+" healed "+targetPlayer.getName()+" sparkles!");
//I know the code is called with valid targets due to the debug line.
```

```
Block b; //obtain Block b
Particle part = new Particle(b.getX(), b.getY(), b.getZ(), Particle.Type.LAVASPARK);
b.getWorld().spawnParticle(part);
//I know block is valid as I play AuxiliarySoundEffect MOBSPAWNER_FLAMES at the same time and they work fine.
```

**Comment by BluXDragon** [comment]
Updated as we figured out the problem with BONE_MEAL.

**Comment by ayyron-dev** [comment]
well, it seems like, you're spawning it inside a block

**Comment by BluXDragon** [comment]
I guess some context would have been a good idea.
I did that in a LineTracer, iterating through the getNextBlock() method. Through the air. I knew it worked as I had previously done it with AuxEffect MobspawnerFlames

**Comment by ayyron-dev** [comment]
Ok.that makes sense then. UK try to be productive tomorrow
