### ISSUE TITLE
Request: Implement scoreboard

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#75]
So that it is not forgotten.
If you need me to do any specific info gathering do tell :D

**Comment by damagefilter** [comment]
If you think you can manage to actually pull off the thing yourself, please do and make a PR.
Otherwise, we'll do it asap'ish

**Comment by BluXDragon** [comment]
Yeah I can't say I'll know what I'm doing if I try that :P

**Comment by ayyron-dev** [comment]
for an update, I have this about half done, been busy lately :/
