### ISSUE TITLE
Inventory.removeItem(item); error

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#76]
http://pastebin.com/pJ6hExuX

The above error is thrown by the below code upon opening chests, dispensers, etc. Anything except player inventory (the hook isn't called when opening player inventory apparently).

```
    @HookHandler
    public void onInventory(InventoryHook hook){
        Player player = hook.getPlayer();
        Inventory inv = hook.getInventory();
        for (Item i : inv.getContents()){
            if (i == null)continue;
            player.sendMessage("§c"+i.getDisplayName());
            inv.removeItem(i);
            inv.update();
            }
        }
    }
```

**Comment by darkdiplomat** [comment]
Fixed with https://github.com/FallenMoonNetwork/CanaryRecode/commit/663ffb6827b1fbf73da1b1fac4557336a62f4b52
