### ISSUE TITLE
Request: Fancy new version of getPlayerListEntry

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#79]
This, but on recode.
https://github.com/FallenMoonNetwork/CanaryMod/blob/crow/src/PluginListener.java#L1173
Preferably it should be moved/modified to give us a List< PlayerlistEntry >, and that we can instantiate PlayerlistEntry, for the purpose of adding "players" to the list. Or however you want to do it.

**Comment by ayyron-dev** [comment]
kind of like how the mob spawners/mob spawner entries work?

**Comment by darkdiplomat** [comment]
Just a note on this. There is no official list for PlayerListEntry, its all created dynamicly.
I can however, open a way to send a PlayerListEntry outside of the auto-update stuff. This should also allow fake entries to be sent (can't guarantee this function though)

**Comment by BluXDragon** [comment]
So there's no real way for the server to know when the player presses TAB?

**Comment by darkdiplomat** [comment]
Correct. The server doesn't know when player's look at the list, it just sends packets out periodically to update the information the Client has stored. 

(Useless Information: I set my player list to P since I use Tab for inventory :3 )

**Comment by BluXDragon** [comment]
Then perhaps a hook for when the automation sending fires off, and we can have a list for PlayerListEntry there?

**Comment by darkdiplomat** [comment]
I can't give a list of entries as they are created as needed, I can however move the hook around and add who is to receive the entry

**Comment by darkdiplomat** [comment]
Also, As I was saying earlier, I added sendPlayerListEntry(PlayerListEntry) to Server and will add a method to Player to do the same, so you can send a entries as needed.
