### ISSUE TITLE
onCraft additions

### ISSUE THREAD

**Issue by gregcarlin** [FallenMoonNetwork/CanaryLib#8]
I would really like to see the following things added to the onCraft hook:
1) Make it a cancelable hook
2) Retrieve the items in the crafting slots and their locations (probably in a small array)

**Comment by Jarvix** [comment]
2) You want a crafting API? :)

**Comment by gregcarlin** [comment]
Well, I've always wanted the ability to do more stuff with crafting, seeing as it's a significant part of the game. I found the onCraft hook and did a little testing with it, but all it seems to do is monitor what people are crafting. So I basically do want a deeper API, along the lines of what I explained.

**Comment by darkdiplomat** [comment]
you can actually cancel it by setting the item to null, and I'll see about getting the items in the crafting matrix

**Comment by damagefilter** [comment]
I put Container<> on Workbench, should be able to access the crafting grid from there. I'll test around.

**Comment by damagefilter** [comment]
So, this is on hold until we fixed the crafting issue.

**Comment by gregcarlin** [comment]
Take your time! I'd much rather it be done correctly.

**Comment by damagefilter** [comment]
Done, closing :)
