### ISSUE TITLE
CommandBlock permissions

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#82]
Instead of defining specific commands a CommandBlock can use, perhaps we should opt instead to be able to define what **permissions** CommandBlock's have by default? Be it typing out the list of default permissions or by giving the CommandBlock a "Group".

Essentially, I request that CommandHooks **do not** ignore permissions, and that we define what **permissions** a command block has by default rather than what specific commands they can use. However way would be best to do this.

**Comment by damagefilter** [comment]
Smart concept!

I would suggest we add a commandblock-group priperty instead of allowed commands then. this group & hierarchy will be used for permission lookups then.

**Comment by ayyron-dev** [comment]
I second that.

**Comment by damagefilter** [comment]
Implemented!
