### ISSUE TITLE
Bug or not: negative plugin priorities cause plugins to not load?

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#86]
If this is intentional, then I suggest plugins be given a default priority higher than zero. The way it is now, if we want to explicitly set one plugin below all others, we have to increase the priority of every other plugin - including when we add new ones. This is blatantly inconvenient and simply giving plugins a default priority of, say, 10, would fix this.

**Comment by WWOL** [comment]
Pretty sure it's intentional.
Also why not have one plugin at 10, another at 20, 30 and so on. Then when you add another just make it 21 etc.

WWOL

**Comment by damagefilter** [comment]
Is intended behaviour to selectively disable plugins permanently.

**Comment by BluXDragon** [comment]
The issue isn't fixed, problem lies in the description.
@WWOL not sure how you would determine the order of priority they would install, though. That's all well and dandy if you manually put it that way but yeah.

**Comment by damagefilter** [comment]
I changed some things so priorities will be generated in 10-steps
