### ISSUE TITLE
Cloned items are magically NBT linked

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#87]
```
Canary.factory().getItemFactory().newItem(Item);
```

This is used to duplicate items. However, the duplicate item obtained is not an entirely separate item.

The best way to explain this is by example.

If I spawn an item into my inventory using this code;

```
        Item newItem = Canary.factory().getItemFactory().newItem(targetPlayer.getItemHeld());
        targetPlayer.giveItem(newItem);
```

I get the duplicate item. Yay. But then I use a plugin to enchant the original item (AFTER having already cloned it), and the enchantment gets applied to both the original and the clone.
If I apply DisplayName, Lore, or any form of NBT data to one item, it gets applied to the other. God knows what other effects this has (I remember a similar occurrence happening with an old plugin to view inventories).

No errors or anything of the sort.

**Comment by ayyron-dev** [comment]
Probably something wrong on our side.I'll take a look tomorrow.

**Comment by darkdiplomat** [comment]
Well, that's a pretty epic level cloning .

Seriously though, I don't trust that method for cloning. I believe it was meant as a temporarily solution till we could resolve the issue with a real fix.

**Comment by ayyron-dev** [comment]
Fixed with https://github.com/FallenMoonNetwork/CanaryRecode/commit/064b5374fd788a5bb56915991db16ecf488089f3
