### ISSUE TITLE
missing methods

### ISSUE THREAD

**Issue by spenk** [FallenMoonNetwork/CanaryLib#9]
im missing 
player.getLevel();
player.setXP()
warp.getLocation();
Home.getLocation();
player.setCreatetiveMode(boolean); since we have player.isInCreativeMode();

**Comment by Jarvix** [comment]
To set creative mode, use setMode(1). I replace isInCreativeMode with getMode, especially with the new adventure mode in sight.

**Comment by Jarvix** [comment]
Implemented Warp.getLocation(). I dont see any Home class so i cant implement Home.getLocation()
Warp class has a warp() method that takes a Player as argument. It will, if possible, warp the given player to the location. Use that to warp the player.
Added Player.getLevel() and Player.setExperience().

**Comment by spenk** [comment]
dont want to open an new issue but could add 
player.getInventory.getItemFromSlot();
and world.Explode(x,y,z,power);

**Comment by Jarvix** [comment]
Please open a new issue
