### ISSUE TITLE
Player.getInventory().removeItem(item); not respecting NBT data

### ISSUE THREAD

**Issue by BluXDragon** [FallenMoonNetwork/CanaryLib#95]
Best description I have right now is example.

Two sticks are in my hotbar. One in the first slot, one in the second slot.

The stick in the second slot has a metatag "HasTag" value of true, and it has one line of lore "waffles".
The stick in the first slot is vanilla as it gets.

If I use Player.getInventory().removeItem(Player.getItemHeld()); while holding the stick (maybe the method getItemHeld is where the problem lies, actually? I don't know, could be), it kills the first stick.

**Comment by damagefilter** [comment]
One more time.
You hold the first stick in your hand and removeItem(Player.getItemHeld()) removes it?
Sounds like intended behaviour.

Probably not what you mean.
Bro tip for better descriptions:
Use a is-should schema. Like this:
Is:
Stick in hand is not removed by removeItem(Player.getItemHeld())
Should:
Stick should be removed by removeItem(Player.getItemHeld())

Makes thigns easier :)

**Comment by darkdiplomat** [comment]
Remove Item is based on ID and Damage values only, was never intended to be a perfect match and trash

**Comment by BluXDragon** [comment]
My description was awful as I was sleep deprived and leaving at the time of posting it. I just didn't want to forget.
I guess DD's comment ends the issue, since it wasn't intended to be that way then technically it's not an issue.

But in that case, the best way to remove a perfectly matched item would be? (I've tried using slot numbers from the item but it threw spazzes far too often. I'm not able to open my workspace right now though.)

**Comment by BluXDragon** [comment]
Doublepost and the delete button isn't doing anything. God damn this device.

**Comment by damagefilter** [comment]
Can this be closed then?
