### ISSUE TITLE
logger.CanaryLevel: strange values for level constants

### ISSUE THREAD

**Issue by nosefish** [FallenMoonNetwork/CanaryLib#97]
The logger logs every message with a level >= the level set for the logger.
The current order  <code>WARNING > DEBUG > DERP > NOTICE > SERVERMESSAGE > INFO</code> doesn't make much sense to me. When logging at level <code>INFO</code>, I don't expect to see <code>DEBUG</code> or <code>DERP</code> messages.

Expected order: <code>WARNING > NOTICE > SERVERMESSAGE > INFO > DERP > DEBUG</code>

**Comment by damagefilter** [comment]
DERP is a kind of WARNING level (for those special moment warnings) so I would suggest this order:
WARNING > DERP > NOTICE > SERVERMSG > INFO > DEBUG

**Comment by nosefish** [comment]
Sounds good to me. And thanks for clarifying the purpose of the DERP level.
